### ISSUE TITLE
和微信开源的 HardCoder 对比有什么优势？

### ISSUE THREAD

**Issue by drakeet** [MiCode/MiBridge#2]
看起来微信开源的 HardCoder 也能实现同样的效果，而且接口方法也都很类似，并且 HardCoder 适配了更多厂商，详情可见：https://github.com/Tencent/Hardcoder/wiki/FAQ

所以小米现在开源的这个新版有什么优势？

谢谢！

**Comment by GuYunjian-Xiaomi** [comment]
jar包代码是开源的，开发者可以参考开源的代码直接反射调用系统提供的接口，不需要接入任何sdk。

**Comment by drakeet** [comment]
谢谢，不过这有点说不太过去，HardCoder 也是开源的，开发者也可以自行照抄代码（换句话说，也可以不需要任何 jar 包或 SDK，但这意义不大...）。不过我不是抬杠哈，只是想进一步了解是否真的有明显的优势，毕竟对方涵盖更广。无论如何，仍然非常感谢小米能够分享这么一个新的方案，多一种选择，也让大家对此有更多的意识、关注和尝试。
